

== Terms and Definitions

=== Data Cube

Multi-dimensional ("n-D") array of values. Even though it is called a 'cube,' it can be 1-
dimensional, 2-dimensional, 3-dimensional, or higher-dimensional. The dimensions may
be coordinates or enumerations, e.g., categories.


=== Geospatial Coverage Data Cube

A {{Data Cube}} established on basis of a Coverage with a specific grid system for
geospatial data with at least one dimension of spatial or temporal definition.

NOTE: This definition is particular to the concept defined in this Community Practice.


=== Geospatial Coverage Data Cube Service

Online service that provides access and analytics on
{{Geospatial Coverage Data Cube,Geospatial Coverage Data Cubes}}.


=== Coverage

Feature that acts as a function to return values from its range for any direct position
within its spatial, temporal or spatiotemporal domain.

[.source]
<<OGC_2006>>

NOTE: Coverages include regular and irregular grids, point clouds, general meshes.


=== Grid

Network composed of two or more sets of curves in which the members of each set
intersect the members of the other sets in an algorithmic way.

[.source]
<<OGC_2006>>

NOTE: This definition intends to include 1D.


=== Grid cell

Smallest polygonal area established by the intersecting curves of a grid.
